name: CI/CD

on:
  push:
    branches: [ "main" ]  # Деплой после пуша/мержа в main
  pull_request:
    branches: [ "develop" ]  # Проверка сборки для PR из develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm install
      - run: npm run build

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main'  # Деплой только из main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm run build
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
